### PR TITLE
[FieldDefinitions] Support for Sorbet, heredoc descriptions, and shared resolver methods

### PR DESCRIPTION
**Pull request by alex4787**
A few extensions were added to the `FieldDefinitions` to adapt to some issues we encountered linting the codebase at Shopify, namely:
- Support for Sorbet method signatures
- Support for field definitions with heredoc descriptions
- Support for when multiple fields share the same resolver method

I've amalgamated all the changes here as a work-in-progress PR, but before proceeding, I'd like to see if some/all of these are changes that you'd like to see in this gem. Once that's determined, I can break this down into more easily reviewable PRs and make appropriate updates.

### CODE REVIEW

**Comment by DmitryTsepelev** [comment]
Hi @alex4787, thanks for the proposal! I'm definitely open to any proposals since all cops are optional and users can easily turn off ones they don't like 🙂 Can't wait to merge this stuff in!

**Comment by alex4787** [comment]
@DmitryTsepelev Code should be good to merge now, I've split it into three commits (per feature):
- https://github.com/DmitryTsepelev/rubocop-graphql/pull/77/commits/3a9ab8a3145f2f3b71a40add24c651b209b18060 (Sorbet)
- https://github.com/DmitryTsepelev/rubocop-graphql/pull/77/commits/5fb73f849241e7252a22665df4abe02d9b8fa050 (heredoc descriptions)
- https://github.com/DmitryTsepelev/rubocop-graphql/pull/77/commits/811fca4e8c3b71f119c14bdc16f1c7a90367f616 (multiple fields sharing resolvers)

Let me know if there's anything I should fix, or if it'd be better for these to be split into their own PRs.

**Comment by DmitryTsepelev** [comment]
That's impressive, Thank you so much for the hard work! I'm going to merge it in and release the new version right now

**Comment by alex4787** [comment]
No problem! Thank you for being so open to these new additions and the quick responses, appreciate it! We'll be bumping our rubocop-graphql version very shortly for our codebase here 😄

**Pull request merged**
