### PR TITLE
Feature: add "Order" config to cops: OrderedFields, OrderedArguments

### PR DESCRIPTION
**Pull request by TSMMark**
Solves #129

### CODE REVIEW

**Comment by DmitryTsepelev** [comment]
plz ignore edge, it fails on master too

**Comment by TSMMark** [comment]
> plz ignore edge, it fails on master too

Yeah I figured that wasn't something I did.

IMO this is pretty good to go. I tested it on our codebase and it worked as expected! 

The only issue is it warns:

Warning: GraphQL/OrderedArguments does not support Order parameter.

> Supported parameters are:
> 
>   - Enabled
> 
> Warning: GraphQL/OrderedFields does not support Order parameter.
> 
> Supported parameters are:
> 
>   - Enabled
>   - Groups

And I can't find where to configure the allowed parameters lol. You'd think that would be the easy part

**Comment by DmitryTsepelev** [comment]
Maybe we should add a default value to the default.yml like we do for Groups https://github.com/DmitryTsepelev/rubocop-graphql/blob/master/config/default.yml#L149

**Comment by TSMMark** [comment]
> Maybe we should add a default value to the default.yml like we do for Groups https://github.com/DmitryTsepelev/rubocop-graphql/blob/master/config/default.yml#L149

Ah yes of course, that did it! Thanks

**Pull request merged**
